web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app/
  environment:
   NOVE_ENV: development 
   MONGO_URL: mongodb://db:27017/mern-starter
   API_KEY: pt9hmnp4ngx64vaqtck2hxn3
db:
  image: mongo:latest
  ports:
   - "27017:27017"

